source 'https://github.com/CocoaPods/Specs.git'

target 'IMDateScroll', :exclusive => true do
  pod "IMDateScroll", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "IMDateScroll", :path => "../"

  
end
